const PROMPT_DATA = {
  lives: [
    "in the desert",
    "in a shoe",
    "under the bed",
    "in the attic",
    "in the ocean",
    "inside a coconut",
    "inside a pineapple",
    "at the very top of trees",
    "inside a tree",
    "in a bubble",
    "in a flower",
    "under a mushroom",
    "in the garden",
    "inside a book",
    "behind the tv screen",
    "on a mountain",
    "in a mountain",
    "in a snowman",
    "on a snowflake",
    "in an ice cube",
    "inside a rock",
    "under the grass",
    "on a leaf",
    "in a computer",
    "under the sink",
    "in a lake",
    "inside a crystal",
    "on the moon",
    "on the sun",
    "inside a cupcake",
    "inside a spool of thread",
    "inside a ball of yarn",
    "in a man’s beard",
    "in a woman’s purse",
    "inside your ear",
    "in your hair",
    "under the stairs",
    "in a corn husk",
    "in a banana peel",
    "in the refrigerator",
    "on top of a skyscraper",
    "in a raindrop",
    "in the basement",
    "in the forest",
    "inside a hill",
    "in a volcano",
    "on a comet",
    "inside a star",
    "in a cave",
    "on a star",
    "inside a pumpkin",
    "inside a pine cone",
    "inside an acorn",
    "in a can of sardines",
    "in the clouds",
  ],

  size: [
    "could fit inside a thimble",
    "is smaller than an acorn",
    "is bigger than a school bus",
    "is as big as a house",
    "is smaller than a peanut",
    "is as big as a moose",
    "is smaller than a mouse",
    "is larger than a whale",
    "could fit inside a mason jar",
    "is as light as a feather",
    "is smaller then an elephant",
    "is bigger than a pack of cards",
    "could fit under the bathroom sink",
    "fits under your bed",
    "fits in your dresser drawer",
    "sits under your desk"
  ],

  eats: [
    "lollipops",
    "chocolate bars",
    "ice cream",
    "glass",
    "rocks",
    "nails",
    "soap",
    "sponges",
    "sea shells",
    "bananas",
    "grass",
    "flowers",
    "feathers",
    "pencils",
    "dirty socks",
    "tacos",
    "sand",
    "christmas trees",
    "snowflakes",
    "old books",
    "bones",
    "cellphones",
    "house plants",
    "soda cans",
    "old boots",
    "jello",
    "paint",
    "birthday candles",
    "cupcakes",
    "family photos",
    "acorns",
    "peanut shells",
    "corn on the cob",
    "pickles",
    "pumpkins",
    "cactuses",
    "teddy bears",
    "skyscrapers",
    "ice cubes",
    "ear wax",
    "sound",
    "planets",
    "spiders",
    "lawn gnomes",
    "flamingos",
    "bees",
    "eggs",
    "toast",
    "bacon",
    "cars",
    "hair",
    "dust",
    "cookies",
    "soda",
  ],

  travel: [
    "on a bee",
    "on a bird",
    "on a paper airplane",
    "on roller skates",
    "in kangaroo pouches",
    "on a cat",
    "on a dog",
    "on a lizard",
    "on a rocket ship",
    "on a spider",
    "on shooting stars",
    "on a bubble",
    "on falling leaves",
    "on a unicorn",
    "on a shark",
    "on a goat",
    "on a frog",
    "on a porcupine",
    "on dandelion fluff",
    "on a fish",
    "on an earth worm",
    "on a butterfly",
    "on a caterpillar",
    "on a school bus",
    "on smoke particles",
    "on a boat",
    "on the wind",
    "on a snowflake",
    "on flamingos",
    "on a turtle",
    "on sound waves",
    "on a lightning bolt",
    "on a mouse",
    "on a fly",
    "on a hover board",
    "on a elephant",
    "on a unicycle",
    "on a bicycle",
    "on a flame",
    "on a robot",
    "on fireworks",
    "on a lightning bug",
    "on an ant",
    "on waves",
    "on a balloon",
    "on a dinosaur",
    "on a bat",
    "on a snail",
  ],

  extra: [
    "has scales",
    "has 2 legs",
    "has 3 legs",
    "has 4 legs",
    "has 5 legs",
    "has 6 legs",
    "has 7 legs",
    "has 8 legs",
    "has 9 legs",
    "has 10 legs",
    "has 2 arms",
    "has 3 arms",
    "has 4 arms",
    "has 5 arms",
    "has 6 arms",
    "has 7 arms",
    "has 8 arms",
    "has 9 arms",
    "has 10 arms",
    "has 2 teeth",
    "has 3 teeth",
    "has 4 teeth",
    "has 5 teeth",
    "has 6 teeth",
    "has 7 teeth",
    "has 8 teeth",
    "has 9 teeth",
    "has 10 teeth",
    "has 2 eyes",
    "has 3 eyes",
    "has 4 eyes",
    "has 5 eyes",
    "has 6 eyes",
    "has 7 eyes",
    "has 8 eyes",
    "has 9 eyes",
    "has 10 eyes",
    "has sharp claws",
    "has fangs",
    "moves like a liquid",
    "can fly",
    "hops",
    "is sleepy",
    "is super hairy",
    "has a beard",
    "has a mohawk",
    "has whiskers",
    "has arms for legs",
    "has legs for arms",
    "is clumsy",
    "has giant feet",
    "has long flowing hair",
    "has spines",
    "can see in the dark",
    "has 2 heads",
    "has 3 heads",
    "can smell sounds",
    "glows",
    "has large teeth",
    "has big ears",
    "has floppy ears",
    "wears fancy hats",
    "has antennas",
  ],
}

module.exports = PROMPT_DATA